name: Deploy Web
on:
  workflow_dispatch
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Update .env
        run: |
          sed -i 's/DB_DATABASE=/DB_DATABASE=${{ secrets.BOOKLY_DB_DATABASE }}/g' .env
          sed -i 's/DB_USERNAME=/DB_USERNAME=${{ secrets.BOOKLY_DB_USERNAME }}/g' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{ secrets.BOOKLY_DB_PASSWORD }}/g' .env

          
      - name: Update Dependencies
        run: composer update
        
      - name: Install Dependencies
        run: composer install
        
      - name: Generate key
        run: php artisan key:generate
      
      - name: Run Migrations and Seed Database
        run: php artisan migrate:fresh --seed
        
      - name: Upload via FTP by Actions Github
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          delete: "false"
